// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK3JOcbwUwfuxayQNg3qCKxkOkwD8X1CM',
    appId: '1:276253281552:web:01b621510e7ab2cb55a995',
    messagingSenderId: '276253281552',
    projectId: 'grocceryplus',
    authDomain: 'grocceryplus.firebaseapp.com',
    storageBucket: 'grocceryplus.firebasestorage.app',
    measurementId: 'G-XWR309RB48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkqhiOvV5OCi7yozEugEXH3zlkpSTmlcM',
    appId: '1:276253281552:android:5d0f584edd474cd855a995',
    messagingSenderId: '276253281552',
    projectId: 'grocceryplus',
    storageBucket: 'grocceryplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD-UB_wvx50g_NKoeKJYgYvl9cdfVD0gw',
    appId: '1:276253281552:ios:4c2d8bcce45d037155a995',
    messagingSenderId: '276253281552',
    projectId: 'grocceryplus',
    storageBucket: 'grocceryplus.firebasestorage.app',
    iosBundleId: 'com.example.grocceryplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD-UB_wvx50g_NKoeKJYgYvl9cdfVD0gw',
    appId: '1:276253281552:ios:4c2d8bcce45d037155a995',
    messagingSenderId: '276253281552',
    projectId: 'grocceryplus',
    storageBucket: 'grocceryplus.firebasestorage.app',
    iosBundleId: 'com.example.grocceryplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK3JOcbwUwfuxayQNg3qCKxkOkwD8X1CM',
    appId: '1:276253281552:web:0a3b7a02232c631555a995',
    messagingSenderId: '276253281552',
    projectId: 'grocceryplus',
    authDomain: 'grocceryplus.firebaseapp.com',
    storageBucket: 'grocceryplus.firebasestorage.app',
    measurementId: 'G-GLPBFEXWBQ',
  );
}
